### ISSUE TITLE
Does code in ploneconf.site_sneak take precedence over code examples in sphinx docs?

### ISSUE THREAD

**Issue by fulv** [plone/training#118]
I was looking at https://github.com/plone/training/blob/plone5/user_generated_content.rst, and some of the code examples there are slightly different than the code in ploneconf.site_sneak.  I assume that this is the case elsewhere in the sphinx docs, too.  @pbauer, do you have a guideline for the "source of truth" when there are differences?  Or do we have to look at latest commit dates between the two, to find out, case by case?  (I assume we want the code to be the same.)

**Comment by pbauer** [comment]
@fulv the answer is sadly "it depends". The code and the docs should always be ins sync. If they are not it is due to a forgotten commit and the commit dates mitghe help figuring out which is the currently "best" version. If that is not conclusive you have to decide which version is best for teaching and quality.
