### ISSUE TITLE
Migration from plone 5.0 to 5.0.1dev0 does not work

### ISSUE THREAD

**Issue by pabo3000** [plone/training#153]
After a git pull on the trianing repo I did the buildout again. But the migration did not work. I will use a new Database.

Zurzeit aktive Konfiguration
5011
Die letzte Konfiguration
5012

Aktualisierungsreport

Starting the migration from version: 5011
End of upgrade path, main migration has finished.
The upgrade path did NOT reach current version.
Migration has failed
Versionsübersicht

Plone 5.0.1.dev0
Zope 2.13.23
Python 2.7.10 (default, Sep 16 2015, 13:03:34) [GCC 4.9.2]

**Comment by fredvd** [comment]
@pabo3000 I just installed the training buidout and didn't have this problem, but I think @thet fixed this issue by pinning our checkout from Products.CMFPlone to version 5.0 yesterday with 796d35b0d0155da13070140a7c77f491f43e57e0

**Comment by fredvd** [comment]
Sorry, I was not checking, it's the upgrade that's tripping you up.   @pabo3000 As long as you haven't put any content in there it's ok to throw away the content database monday morning and add a fresh one, then you don't have the migration issue

@thet Do you need the latest revision of Products.CMFPlone for your training?  Because it also means we need to pull in plone.app.upgrade to solve this. But starting with a fresh db on monday seems the best solution I guess.
