### ISSUE TITLE
More specific instructions for `bower init`

### ISSUE THREAD

**Issue by fulv** [plone/training#172]
Under http://training.plone.org/5/theming/theme-package.html#load-less-parts-of-bootstrap, it says `After filling some questions, we have a bower config file called bower.json. `  Some of the questions are not obvious for a first-time `bower` user:

- does the `name` matter?
- does the `main file` matter?
- it asks `what types of modules does this package expose?` (options:  `amd`, `es6`, `globals`, `node`, `yui`)
- `set currently installed components as dependencies?`

We should add clearer instructions.  @MrTango, @simahawk, if you reply here, I or someone else will update the training source.

**Comment by MrTango** [comment]
Yes this is confusing, the most of the questions does not matter, because they are for creating a bower package, and we only need the dependencies here. I think i'll change that step into providing just a basic bower file, which one can copy. I still have it on my list to rewrite a bigger part of the training, soon as i can find a little time for it ;)

**Comment by fulv** [comment]
@MrTango would you say that the `types of modules this package exposes (amd, es6, globals, node, yui)` don't matter?  In other words, they can all be left unchecked?

**Comment by MrTango** [comment]
yes
