### ISSUE TITLE
isn't API part of Plone 5?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/training#234]
Is this still correct? https://github.com/plone/training/blob/43ec3c695129371f994c8b9c667077bad7213765/mastering_plone/api.rst#L33 "plone.api is not yet part of the Plone core. Therefore you will not see any use of plone.api in Plone itself. It will be part of Plone 5."

**Comment by gforcada** [comment]
Sort of, it's part of Plone core, i.e. is part of Plone when you install it, but Plone core does not use it (to avoid circular dependencies).

If we want the core to use it we have to either copy all the code that plone.api depends on in itself, or make that in each case by case a circular dependency is not introduced (which is really difficult given Python's dynamic nature).

It's more a tool for integrators/developers to be efficient and have a nice API to hide all the complexity, rather than a framework tool to base on.

I would love to use it in core, but the dependency problem is quite a problematic one.

**Comment by tkimnguyen** [comment]
Ah thanks for clarifying, @gforcada ! Perhaps I will reword that section a bit then.
