### ISSUE TITLE
Question: Opsworks Chef 12

### ISSUE THREAD

**Issue by svx** [plone/training#274]
@alecpm 

I am busy with updating the training docs, is the following still valid ? 

> The latest Opsworks codebase requires Chef 12. The Python cookbooks are currently only tested on Chef 11.

> Running Opsworks on Ubuntu Xenial instances requires using the latest Chef 12 version.

Thanks a lot !!!

**Comment by alecpm** [comment]
Yes it is. I’m planning to try out the new Chef 12 infrastructure (which is radically different from the original OpsWorks Stack implementation in that it uses Chef Server rather than Chef Solo) in the next couple months. It looks like running Plone 5.1 will probably require making that shift, since it requires a newer python version than the one included with Trusty.

**Comment by stevepiercy** [comment]
Closing as won't fix because this training has been archived.
