### ISSUE TITLE
How will we handle invalid JSON snippets?

### ISSUE THREAD

**Issue by jean** [plone/training#290]
In `angular.rst` we have 

```json
.. code-block:: json

    "scripts": {
    ...
    "update-backend": "plonetheme-upload --enable plonecustom http://whatever.herokuapp.com/Plone"
    }
```

That generates a warning and doesn't highlight. 

This works, but it's less clear about how this snippet fits into the target file, by implying that `scripts` has no siblings and `update-backend` has only one key:

```json
{"scripts": {
  "update-backend": "plonetheme-upload --enable plonecustom http://whatever.herokuapp.com/Plone"                                         }}
```

For a short snippet like that, maybe silencing the warning in that specific case would make sense. Is there a better way?

**Comment by svx** [comment]
Related to: https://github.com/plone/training/pull/285.

**Comment by fulv** [comment]
In this particular case, I think it would make sense to use `.. code-block:: js`, instead of `json`.  And for snippets of JSON this might be a good enough workaround, since there probably isn't any text that needs to be highlighted, anyway.  

Perhaps `.. code-block:: json` makes sense when you are using complete json data structures, and you want to lean on the strict checks to ensure you didn't mess it up somehow.
