### ISSUE TITLE
React: Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/training#423]
In paragraph 7.1, [Store Questions And Answers In The State](https://training.plone.org/5/react/state.html#store-questions-and-answers-in-the-state), we iterate over the items using the `map` function. After this, when you run `yarn test` you get a warning:

```
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `App`. See https://fb.me/react-warning-keys for more information.
          in FaqItem (at App.js:25)
          in App (at App.test.js:7)
```

This is solved in chapter 9. We may want to warn the reader. Maybe a note like this in paragraph 7.1:

> When running `yarn test` you may now get a warning: 'Each child in a list should have a unique "key" prop.' Do not worry about that for now: we will fix this in chapter 9.

**Comment by mauritsvanrees** [comment]
Two months ago I apparently thought I had solved this with an extra id in `FaqItem.jsx`:

    <li id={this.props.index} className="faq-item">

But I still see the warning in the console.

**Comment by ichim-david** [comment]
@mauritsvanrees this is happening because it's missing the key property.
On React docs it's explained why it's needed:
https://reactjs.org/docs/reconciliation.html#keys

The tutorial needs to be updated from chapter 5 when it starts to map the state
array of FaqItems to also pass the **index** and for the index to be used also for the **key**.
https://training.plone.org/5/react/state.html#store-questions-and-answers-in-the-state

Only in chapter 9 is the index parameter passed to the map function
https://training.plone.org/5/react/callbacks.html#write-a-dummy-delete-handler
So here it would make possibly even more sense to add the key.

As such the final snippet would be
`
 <FaqItem
            question={item.question}
            answer={item.answer}
            index={index}
            key={index}
            onDelete={this.onDelete}
          />
`

If time permits perhaps in the future this reply will result in a pull request to the training to add a detail about this
issue and to make sure the examples all contain the key prop as it's a bad look to have a tutorial with console
errors or warnings.

**Comment by TC5022** [comment]
May I work on this issue @mauritsvanrees @ichim-david?

**Comment by mauritsvanrees** [comment]
@TC5022 I would say go ahead! Thanks.

Before a patch can be merged though, you would need to sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), otherwise we cannot accept a contribution.

I am actually not completely sure if this is also required for the documentation or training. Does anyone know? cc @polyester

**Comment by stevepiercy** [comment]
> I am actually not completely sure if this is also required for the documentation or training. Does anyone know?

Yes, it is required for everything under the Plone organization, including documentation and trainings.

See https://training.plone.org/5/contributing/index.html#granting-permission-to-publish

**Comment by TC5022** [comment]
Thankyou @mauritsvanrees. I have filled out the agreement and will be mailing it soon. Looking forward to being a part of the community!

**Comment by stevepiercy** [comment]
@TC5022 thank you! While you are waiting for the agreement to be processed, you are welcome to work on this issue and submit a pull request. When your pull request is approved, and your agreement is processed, then your pull request can be merged.
