### ISSUE TITLE
Find Plone trainings

### ISSUE THREAD

**Issue by ksuess** [plone/training#503]
Plone is cool. 
@plone/marketing-communications would you help to kick out these boring google / bing / whatever search result titles **and descriptions**? and help kick out outdated pages?

**Google "Plone training"**

![image](https://user-images.githubusercontent.com/1144737/131174556-4b0953a7-86c4-4019-b93f-66515c7f7e32.png)

**Google "Plone tutorial"**

![Plone_tutorial_-_Google_Suche](https://user-images.githubusercontent.com/1144737/131176483-d58b7ca4-fc75-4810-85ed-c7c8ebce96b8.jpg)

**Comment by fredvd** [comment]
To make the training results in search engine listings less boring, we'll need to add metadata to the html that is generated by the training docs builder.  A bit like collective.ogtags and also Plone 5.x are adding.  

More in general, when you search on plone.org itself and also through for example Google, a lot of old irrelevant content from 10-12 years comes up regularly first.   I'm against removing the content alltogether. But maybe we should 'hide' part of the older content from at least external search engines by removing the pages from the sitemap.xml.gz and add a 'no index' to that content. 

Basically that happens to content with an expiry date set in the past. But the problem is there that also gets hidden in local Plone search results iirc.  We could clean up it up generic by filtering out all content older than 4-6 years. Or adding a workflow state archived. In the local search results an option could be added (off by default) to also search through 'archived' content. 

But this does mean some development/customisation on the www.plone.org stack.

Prioritising Plone 5 docs to 4/3 subsections on docs.plone.org to have more weight/show up first in search results: I have no idea. I would expect that the /3/en/ and /4/en subpaths were once on the top level so link authority should be less than the current plone 5 docs on / .  And in general for earch version the documentation were only extended/clarified, not reduced in text/size.  Maybe the age of the older pages is taken into account and transported/remembered for the new paths?

**Comment by fredvd** [comment]
@rioksane ^^

**Comment by stevepiercy** [comment]
We need to add this Sphinx extension:
https://github.com/wpilibsuite/sphinxext-opengraph

I only learned about it because the contributor accidentally `@`-ed me in the issue tracker for RTD, which subscribed me to it.
https://github.com/readthedocs/readthedocs.org/issues/1758

To get better results, every page's first N characters (whatever we configure for `ogp_description_length`) must be the page description on every page.

**Comment by stevepiercy** [comment]
If however we want to have full control over every page, instead of a quick configuration option, then we should use the built-in support from [docutils' `meta` tag](https://docutils.sourceforge.io/docs/ref/rst/directives.html#metadata).

Is automatic good enough? If not, would authors add the meta tags for every page?

I am curious what would happen when both are enabled.

**Comment by stevepiercy** [comment]
Are there [configuration items](https://github.com/plone/training/issues/503#issuecomment-907614961) in search engines that someone manages? Please speak up.

If not, I think we can close this issue in favor of https://github.com/plone/training/issues/529 and https://github.com/plone/training/issues/519.

**Comment by ksuess** [comment]
Even if i think the title of this issue is still worth an issue, the description I wrote and the screenshots do not fit at all.
The question is: Do developers find the chapters of the training or the chapters of the Plone docs they need?

One step in this direction is to see training chapters with **its chapter title and the training title** in search results of search engines.
`<topic> | <training title> | Plone Training`
This is done with the relaunch.

![plone_block_-_Google_Search](https://user-images.githubusercontent.com/1144737/134046288-eca6e43e-3428-49bc-8fc2-ca299f92f602.png)

The next step would be to have a narrative description for chapters in search results of search engines.
This step is handled in #519 and #529.
