### ISSUE TITLE
[Training "Volto"] Update instructions on how to get a backend (page /volto/bootstrap.html)

### ISSUE THREAD

**Issue by ksuess** [plone/training#723]
Backend as docker container. I think plone.org/download is not recommended anymore.
Maybe just more or less a link to https://6.docs.plone.org/install/index.html

**Comment by SaiRev0** [comment]
I think we should add the use of a docker container for the frontend and backend link in [plone.org/download](https://plone.org/download) as well because its the main website people generally visit when searching for plone. It will be a bit difficult for a general user to find the installation part in the doc only.

I think we should change the content of the page rather than removing it

These are just my take, we can sure have some discussion about it further

**Comment by ksuess** [comment]
> I think we should add the use of a docker container for the frontend and backend link in [plone.org/download](https://plone.org/download) as well because its the main website people generally visit when searching for plone. It will be a bit difficult for a general user to find the installation part in the doc only.
Yes, definitly. Can you open an issue about replacing the "Download" section with an "Installation" section on https://github.com/plone/plone.org?

**Comment by stevepiercy** [comment]
> I think we should add the use of a docker container for the frontend and backend link in [plone.org/download](https://plone.org/download) as well because its the main website people generally visit when searching for plone.

I think the concept of "downloading" Plone is a relic left over from when it was still a thing. It has not kept up with using containers. We'll have to push that discussion over to both the Release Team and Marketing Team to resolve.

Back to this issue, updating `volto/bootstrap.md`, I agree that using containers is the way forward.

**Comment by SaiRev0** [comment]
@ksuess Sure I have opened the issue in that repo plone/plone.org#103
