### ISSUE TITLE
Training title and chapter titile in sticky topbar title is missing

### ISSUE THREAD

**Issue by ksuess** [plone/training#777]
… after upgrade of the theme.

![Cursor_and_TMMenuExtra_and_Item-0_and_Item-0_and_Item-0](https://github.com/plone/training/assets/1144737/8f94c5ad-a1e9-4e3e-9039-271edcaf835a)

See [PR](https://github.com/plone/training/pull/622/) for bringing it back.

**Comment by stevepiercy** [comment]
I don't understand. You provide a screenshot for documentation, not training. Training supports a sticky navbar. This issue is in the training repo.

**Comment by stevepiercy** [comment]
FTR, if we maintain a customization, I want to make sure that the stack supports it already. It appears that both the Sphinx Book Theme (example: https://sphinx-book-theme.readthedocs.io/en/latest/contributing/setup.html) and PyData Theme supports a sticky navbar (example: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html) with slightly different implementations. I think we should endeavor to copy what the Sphinx Book Theme does, because it is the immediate parent to our theme. Documentation has not been upgraded to the latest versions of themes.

**Comment by ksuess** [comment]
Training title and chapter title in sticky topbar shows the reader where he/she is. This is really helpful in a documentation of several trainings with many chapters.

I updated the screenshot in the issue description and the issue title. Should be clear now what I mean.

**Comment by stevepiercy** [comment]
Thanks for the clarification. I agree that would be a good enhancement.
