### ISSUE TITLE
Linkcheck is preventing training update

### ISSUE THREAD

**Issue by ksuess** [plone/training#780]
Let's think about a less restrictive check of broken links. 
Especially during the hot time of two weeks before and including time of conference.

link check

**Comment by stevepiercy** [comment]
Which links are broken? We can add them to `linkcheck_ignore`, if they are unreliable, or remove them. The Internet Archive is unreliable, and those can go into `linkcheck_ignore`. All others need to be evaluated.

I don't want to remove linkcheck because it provides more benefits than obstacles. I don't want bad links getting into the trainings. That is not good for visitors.

**Comment by stevepiercy** [comment]
@ksuess I'm closing this issue due to no response. Feel free to reopen with a list of broken links that need to be added to `linkcheck_ignore`. We could also temporarily disable `linkcheck_broken` during the rush before PloneConf.
